version: 2.1

orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    description: Runs unit tests and instrumented tests
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.04.1
    steps:
      - checkout
      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - android/run-tests
         
      - android/save-gradle-cache:
          cache-prefix: v1a 
  build:
    description: builds the application
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.04.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86




# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test-workflow:
    jobs:
      - test
      - android/run-ui-tests:
          executor:
            name: android/android-machine
            resource-class: large
            tag: 2023.04.1
      - build
    
