version: 2.1

orbs:
  android: circleci/android@2.3.0
jobs:
  test-granular:
    description: using a granular command to set up emulators and Runs unit tests and instrumented tests
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.04.1
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - android/run-tests:
          test-command: ./gradlew test
      - android/run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
         
      - android/save-gradle-cache:
          cache-prefix: v1a 
  # test-convenience:
  #   description: using the convenience start emulator and run tests command
  #   executor:
  #     name: android/android-machine
  #     resource-class: large
  #     tag: 2023.04.1
  #   steps:
  #     - checkout
  #     - android/start-emulator-and-run-tests:
  #         test-command: chmod +x gradlew
  #         system-image: system-images;android-29;default;x86




# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test-workflow:
    jobs:
      - test-granular
      # - android/build:
      #     executor:
      #       name: android/android-machine
      #       resource-class: large
      #       tag: 2023.04.1

      # - android/run-ui-tests:
      #     executor:
      #       name: android/android-machine
      #       resource-class: large
      #       tag: 2023.04.1
      #     test-command: |
      #       chmod +x gradlew
      #       ./gradlew connectedDebugAndroidTest
      # - test-convenience
    
